display "Reloading Config..."
# bind-key w run-shell -b "$XDG_CONFIG_HOME/tmux/plugins/tmux-fzf/scripts/window.sh switch"
# bind-key s run-shell -b "$XDG_CONFIG_HOME/tmux/plugins/tmux-fzf/scripts/session.sh switch"

# unbind C-s
# set -g prefix C-b
# bind C-b send-prefix

set -s set-clipboard on
# set -s set-clipboard external
# set -s set-clipboard off

bind -n S-Enter send-keys Escape "[13;2u"
bind -n C-Enter send-keys Escape "[13;5u"

bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf" \; display "Config reloaded!"

bind-key -n C-s run-shell -b "$XDG_CONFIG_HOME/tmux/sessions/sessions.sh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
