set -g default-shell /opt/homebrew/bin/fish
set -g detach-on-destroy off
set -g mouse on
set set-clipboard on
set extended-keys on

set -g base-index 1
set -g pane-base-index 1

set -g escape-time 0

# Status bar

set -g status-right "#[align=absolute-centre] #[fg=white,nobold]#S #[align=right]"
set -ga status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\ 📅 %d.%m.%y 🕰  %H:%M "
# set -g status-right-length 65

set -g status-style bg=default,fg=black,bright
set -g status-left " "
# set -g status-right "#[fg=white,nobold]#S "
set -g status-right-length 150
set -g status-position bottom

# Window Buttons
set -g window-status-format "#{?window_zoomed_flag,[Zoomed] ,}#I: #W"
set -g window-status-current-format "#{?window_zoomed_flag,[Zoomed] ,}#I: #W"
set -g window-status-current-style fg=green
set -g window-status-bell-style fg=red
set -g renumber-windows on

# Window borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=green

# Enable S-Enter and C-Enter modifiers
bind -n S-Enter send-keys Escape "[13;2u"
bind -n C-Enter send-keys Escape "[13;5u"

# set-environment -g XDG_CONFIG_HOME "/Users/cesar.enrique/.config"

# Keybindings

# Using vim keybindings for selection and copy
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

# Next/Prev windows (Tabs)
bind-key -n C-Tab next-window
bind-key -n C-BTab previous-window

# Spliting panes
bind-key -n C-S-j split-window -v
bind-key -n C-S-k split-window -v -b
bind-key -n C-S-l split-window -h
bind-key -n C-S-h split-window -h -b

# Close panes
bind-key -n C-S-x kill-pane
bind-key -n C-S-o kill-pane -a

# Switch to last session
bind-key -n C-S-r switch-client -l

# Session picker with fzf
# bind-key -n C-S-s run-shell -b "/opt/homebrew/bin/fish -c sessionizer" # This is slower
bind-key -n C-S-s run-shell -b "/Users/cesar.enrique/.config/tmux/sessions/sessions.sh"

# Worktree picker
bind-key -n C-S-w run-shell -b "/Users/cesar.enrique/.config/tmux/sessions/worktree.sh"

# Reload config
bind r display "Reloading Config..." \; source-file "/Users/cesar.enrique/.config/tmux/tmux.conf" \; display "Config reloaded!"

# Undercurl
set -g default-terminal "xterm-ghostty"
set -as terminal-overrides ',*256col*:RGB'
set -as terminal-overrides ',*:sitm=\E[3m' # Italics support for older ncurses
set -as terminal-overrides ',*:smxx=\E[9m' # Strikeout
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mrjones2014/smart-splits.nvim'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "/Users/cesar.enrique/.config/tmux/plugins/tpm/tpm"
